import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("bank_customers.csv")

print(df.head())
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df.duplicated().sum())

average_balance = df["Balance"].mean()
median_balance = df["Balance"].median()
highest_balance = df["Balance"].max()
lowest_balance = df["Balance"].min()
average_age = df["Age"].mean()

gender_count = df["Gender"].value_counts()
gender_balance = df.groupby("Gender")["Balance"].mean().sort_values(ascending=False)
occupation_balance = df.groupby("Occupation")["Balance"].mean().sort_values(ascending=False)
account_type_count = df["Account_Type"].value_counts()
branch_balance = df.groupby("Branch")["Balance"].mean().sort_values(ascending=False)
city_balance = df.groupby("City")["Balance"].mean().sort_values(ascending=False)

print("Average Balance:", round(average_balance, 2))
print("Median Balance:", round(median_balance, 2))
print("Highest Balance:", highest_balance)
print("Lowest Balance:", lowest_balance)
print("Average Age:", round(average_age, 2))
print("Highest Balance Gender:", gender_balance.idxmax())
print("Highest Balance Occupation:", occupation_balance.idxmax())
print("Most Common Account Type:", account_type_count.idxmax())
print("Highest Balance Branch:", branch_balance.idxmax())
print("Highest Balance City:", city_balance.idxmax())

plt.figure(figsize=(8, 5))
df["Balance"].plot(kind="hist", bins=10)
plt.title("Customer Balance Distribution")
plt.xlabel("Account Balance")
plt.ylabel("Number of Customers")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
gender_count.plot(kind="bar")
plt.title("Customers by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Customers")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
gender_balance.plot(kind="bar")
plt.title("Average Balance by Gender")
plt.xlabel("Gender")
plt.ylabel("Average Balance")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(9, 5))
account_type_count.plot(kind="bar")
plt.title("Account Type Distribution")
plt.xlabel("Account Type")
plt.ylabel("Number of Customers")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
occupation_balance.plot(kind="bar")
plt.title("Average Balance by Occupation")
plt.xlabel("Occupation")
plt.ylabel("Average Balance")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(9, 5))
branch_balance.plot(kind="bar")
plt.title("Average Balance by Branch")
plt.xlabel("Branch")
plt.ylabel("Average Balance")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
plt.scatter(df["Age"], df["Balance"])
plt.title("Age vs Account Balance")
plt.xlabel("Age")
plt.ylabel("Account Balance")
plt.tight_layout()
plt.show()

top_customers = df.sort_values("Balance", ascending=False).head(10)

plt.figure(figsize=(10, 5))
plt.bar(top_customers["Customer_Name"], top_customers["Balance"])
plt.title("Top 10 Customers by Account Balance")
plt.xlabel("Customer")
plt.ylabel("Account Balance")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print("Top 10 Customers:")
print(top_customers[["Customer_ID", "Customer_Name", "City", "Account_Type", "Balance"]])

print("Balance Range:", highest_balance - lowest_balance)
print("Balance Standard Deviation:", round(df["Balance"].std(), 2))